<NewDataSet>
  <Table>
    <id>229</id>
    <jobid>cn=system_syncab,ou=jobs,ou=gwopennode(10.10.23.115),o=netmail115</jobid>
    <jobdatetime>2012-05-25 13:17:07</jobdatetime>
    <logtimestamp>2012-05-25 13:17:23</logtimestamp>
    <account>admin</account>
    <errorsource>m+archive</errorsource>
    <errordescription>exception has been thrown by the target of an invocation.</errordescription>
    <errorstacktrace>   at tma.library.jobs.gwsyncabjob.c85295ce5f38e62205e2f297024a79330(addressbook c2568d39d3e14f3ca0e72b0900177b696)</errorstacktrace>
    <messageid />
    <messagesubject />
    <messagecreationdate />
  </Table>
  <Table>
    <id>228</id>
    <jobid>cn=system_syncab,ou=jobs,ou=gwopennode(10.10.23.115),o=netmail115</jobid>
    <jobdatetime>2012-05-25 13:17:07</jobdatetime>
    <logtimestamp>2012-05-25 13:17:23</logtimestamp>
    <account>admin</account>
    <errorsource>m+archive</errorsource>
    <errordescription>the external map was configured but the dll cannot be instanciated...  exception has been thrown by the target of an invocation.</errordescription>
    <errorstacktrace>   at tma.library.jobs.usermapbase.greateinstance(string sourcetype, string sourceconfig)
   at tma.library.jobs.gwsyncabjob.c85295ce5f38e62205e2f297024a79330(addressbook c2568d39d3e14f3ca0e72b0900177b696)</errorstacktrace>
    <messageid />
    <messagesubject />
    <messagecreationdate />
  </Table>
</NewDataSet>